NumPy - Numerical Python

Advantages of Numpy Arrays:

1. Allows several Mathematical Operations
2. Faster operations

In [1]:
import numpy as np

List vs Numpy - Time Taken

In [2]:
from time import process_time

Time taken by a list

In [3]:
python_list = [i for i in range(10000)]

start_time = process_time()

python_list = [i+5 for i in python_list]

end_time = process_time()

print(end_time - start_time)

0.0017497069999998782


In [4]:
np_array = np.array([i for i in range(10000)])

start_time = process_time()

np_array += 5  

end_time = process_time()

print(end_time - start_time)

0.000423568999999846


Numpy Arrays

In [5]:
# list
list1 = [1,2,3,4,5]
print(list1)
type(list1)

[1, 2, 3, 4, 5]


list

In [6]:
np_array = np.array([1,2,3,4,5])
print(np_array)
type(np_array)

[1 2 3 4 5]


numpy.ndarray

In [7]:
# creating a 1 dim array
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [8]:
a.shape

(4,)

In [9]:
b = np.array([(1,2,3,4),(5,6,7,8)])
print(b)

[[1 2 3 4]
 [5 6 7 8]]


In [10]:
b.shape

(2, 4)

In [11]:
c = np.array([(1,2,3,4),(5,6,7,8)],dtype=float)
print(c)

[[1. 2. 3. 4.]
 [5. 6. 7. 8.]]


Initial Placeholders in numpy arrays

In [12]:
# create a numpy array of Zeros
x = np.zeros((4,5))
print(x)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [13]:
# create a numpy array of ones
y = np.ones((3,3))
print(y)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [14]:
# array of a particular value
z = np.full((5,4),5)
print(z)

[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]


In [15]:
# create an identity matrix
a = np.eye(5)
print(a)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [16]:
# create a numpy array with random values
b = np.random.random((3,4))
print(b)

[[0.91603128 0.50184154 0.49790515 0.84344986]
 [0.14678941 0.30735634 0.07801443 0.68080718]
 [0.40759142 0.53354911 0.09774772 0.22190049]]


In [17]:
# random integer values array within a specific range
c = np.random.randint(10,100,(3,5))
print(c)

[[22 31 47 44 89]
 [76 47 71 59 60]
 [13 37 60 70 81]]


In [18]:
# array of evenly spaced values --> specifying the number of values required
d = np.linspace(10,30,5)
print(d)

[10. 15. 20. 25. 30.]


In [19]:
# array of evenly spaced values --> specifying the step
e = np.arange(10,30,5)
print(e)

[10 15 20 25]


In [20]:
# convert a list to a numpy array
list2 = [10,20,20,20,50]

np_array = np.asarray(list2)
print(np_array)
type(np_array)

[10 20 20 20 50]


numpy.ndarray

Analysing a numpy array

In [21]:
c = np.random.randint(10,90,(5,5))
print(c)

[[69 47 76 41 51]
 [54 42 87 31 78]
 [36 86 60 61 71]
 [88 46 33 11 12]
 [38 45 32 36 74]]


In [22]:
# array dimension
print(c.shape)

(5, 5)


In [23]:
# number of dimensions
print(c.ndim)

2


In [24]:
# number of elements in an array
print(c.size)

25


In [25]:
# checking the data type of the values in the array
print(c.dtype)

int64


Mathematical operations on a np array

In [26]:
list1 = [1,2,3,4,5]
list2 = [6,7,8,9,10]

print(list1 + list2)    # concatenate or joins two list

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


In [27]:
a = np.random.randint(0,10,(3,3))
b = np.random.randint(10,20,(3,3))

In [28]:
print(a)
print(b)

[[9 2 7]
 [0 7 5]
 [9 1 6]]
[[11 12 16]
 [16 10 19]
 [13 11 10]]


In [29]:
print(a+b)
print(a-b)
print(a*b)
print(a/b)

[[20 14 23]
 [16 17 24]
 [22 12 16]]
[[ -2 -10  -9]
 [-16  -3 -14]
 [ -4 -10  -4]]
[[ 99  24 112]
 [  0  70  95]
 [117  11  60]]
[[0.81818182 0.16666667 0.4375    ]
 [0.         0.7        0.26315789]
 [0.69230769 0.09090909 0.6       ]]


In [30]:
a = np.random.randint(0,10,(3,3))
b = np.random.randint(10,20,(3,3))

In [31]:
print(a)
print(b)

[[1 3 2]
 [8 6 6]
 [1 5 7]]
[[12 15 14]
 [15 17 15]
 [15 10 12]]


In [32]:
print(np.add(a,b))
print(np.subtract(a,b))
print(np.multiply(a,b))
print(np.divide(a,b))

[[13 18 16]
 [23 23 21]
 [16 15 19]]
[[-11 -12 -12]
 [ -7 -11  -9]
 [-14  -5  -5]]
[[ 12  45  28]
 [120 102  90]
 [ 15  50  84]]
[[0.08333333 0.2        0.14285714]
 [0.53333333 0.35294118 0.4       ]
 [0.06666667 0.5        0.58333333]]


Array Manipulation

In [33]:
array = np.random.randint(0,10,(2,3))
print(array)
print(array.shape)

[[4 8 6]
 [6 8 7]]
(2, 3)


In [34]:
# transpose
trans = np.transpose(array)
print(trans)
print(trans.shape)

[[4 6]
 [8 8]
 [6 7]]
(3, 2)


In [35]:
array = np.random.randint(0,10,(2,3))
print(array)
print(array.shape)

[[5 1 4]
 [9 5 0]]
(2, 3)


In [36]:
trans2 = array.T
print(trans2)
print(trans2.shape)

[[5 9]
 [1 5]
 [4 0]]
(3, 2)


In [37]:
# reshaping a array
a = np.random.randint(0,10,(2,3))
print(a)
print(a.shape)

[[3 6 0]
 [2 9 6]]
(2, 3)


In [38]:
b = a.reshape(3,2)
print(b)
print(b.shape)

[[3 6]
 [0 2]
 [9 6]]
(3, 2)
